// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWG0mZ9dKzD_Oim6WCTziMk9uVdHYOs_s',
    appId: '1:531215294085:web:dabf47c7743982011d53ec',
    messagingSenderId: '531215294085',
    projectId: 'my-application-789da',
    authDomain: 'my-application-789da.firebaseapp.com',
    storageBucket: 'my-application-789da.appspot.com',
    measurementId: 'G-T51DS8W5WL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh3JBoJtH_yG7jfqrda9PdQkmzWOO0VHI',
    appId: '1:531215294085:android:f633b6a77e3ee5321d53ec',
    messagingSenderId: '531215294085',
    projectId: 'my-application-789da',
    storageBucket: 'my-application-789da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiVac6RImvEUksruC4KlujQ-P6oubOQy4',
    appId: '1:531215294085:ios:6d4171b95069d7e11d53ec',
    messagingSenderId: '531215294085',
    projectId: 'my-application-789da',
    storageBucket: 'my-application-789da.appspot.com',
    iosClientId: '531215294085-dga4qoa1jggcoh5r1nd9j52mifbm2gsb.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiVac6RImvEUksruC4KlujQ-P6oubOQy4',
    appId: '1:531215294085:ios:6d4171b95069d7e11d53ec',
    messagingSenderId: '531215294085',
    projectId: 'my-application-789da',
    storageBucket: 'my-application-789da.appspot.com',
    iosClientId: '531215294085-dga4qoa1jggcoh5r1nd9j52mifbm2gsb.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
